language: python
python:
  - "2.7"
install:
  - pip install yadage[viz]
script:
  -   sudo apt-get install graphviz
  -   yadage-run workdir workflow-physics/workflow.yml -p inputfile='"workflow-physics/input.yml"' -p njobs="2" -p inputdelphes='"workflow-physics/input_delphes.yml"' -d initdir=$PWD --visualize
#  -   yadage-run workdir workflow-ml/workflow.yml -p inputfile='"workflow-ml/inputs/input_ML.yaml"' -p ntrainsamples="5" -p combinedfile='"workflow-ml/inputs/madminer_example_with_data_1.h5"' -d initdir=$PWD --visualize