notifications:
  email:
    recipients:
    - iem244@nyu.edu
sudo: required
services:
- docker
language: python
python:
- '2.7'
install:
- pip install yadage[viz]
script:
- sudo apt-get install graphviz
- yadage-run workdir workflow-physics/workflow.yml -p inputfile='"workflow-physics/input.yml"'
  -p njobs="2" -p inputdelphes='"workflow-physics/input_delphes.yml"' -d initdir=$PWD
  --visualize
- rm -rf workdir
- yadage-run workdir workflow-ml/workflow.yml -p inputfile='"workflow-ml/inputs/input_ML.yaml"'
  -p ntrainsamples="5" -p combinedfile='"workflow-ml/inputs/madminer_example_with_data_1.h5"'
  -d initdir=$PWD --visualize
jobs:
  include:
  - stage: docker
    install:
    - echo none
    script:
    - echo none
    deploy:
      provider: script
      script: sh docker_push.sh
      on:
        branch: master
      condition: "$TRAVIS_PULL_REQUEST = false"
env:
  global:
  - secure: Wdyp1N5Qbzk139zZzYIsdFQy5ShdZuDZ9fhJ+8EvqrKP7aEpBlIr88GYn18yxaPz6Ney+aaW83IUiVaaRE69GxRqriEFWBGOUqyMFZXKyimxbwm1ke9Y1lQdF7oFiY5XwPcNqEDZvhaKpR/O4CSngj0Ef3ft/2pCZ2x8TMH0KrZwEMSf8ayMA80qn8cYJyDpFA1lvHPxdOz/X9q19JHOCEG5hvgS90P1ja7G2PQ1WBI2bHGvbfhhjVXKFipclslyppkb4DcAf9zJD6ZQTFmYKIISZfLmP25o2qJamBF/PhYUh20sOHAQlfPgJXFP5gUSuvOSCEcoBHumM05/b9r0wi+BDVZQ47395oDGm7EVtUZl6NWME1mIkFHWF75m74IjDuSCkVePL/Zv2H6AbJ5PIX1S9obJSNSYBTpYQZMGGkAiacROI6yxHG7cDrP4gkHmsyCeL8Ozg98UjADjLcmIaDfGSStfkgomHbAwQ0kqv+z+dt/bT4+jhlJ3qlbEcyDCgsQgWYqrF5do6f0255Eb+vBDn9fSRJpBAbkw9Do/cWJv2tWyYMZmQystUgZYb/x13PvDHE9YohITlp6HGNf11NeabC+Lyo3iJmm1MHKYADOZixiLW30fRT1WPqqQ0M+jW7oyAD3kFy98zpPsUrEFlKxidxiAG4tC2/YC1weqDlk=
  - secure: ar4PsdYtgh1oOMRWtzb6Hjd5YuZpQuU1BkCo7/t9XV6KTH9L+TMDi/gyDmWE/TvWBTRYyVqFVzHSf969vokqFTWufC7ZJ6HyL9PUoXGp/B1pXIK7Hl/ypeCsUQPrtx2rMAMDqlvDk/CFJr1Btn7CrqdO9JR8WL03kXugrpPTNThOcqdG2i43aeIdHNKeWcDoypSMiJlpSKDJ+ACbUb7H+hIeCy2Qrjc5f7KIPDSxDd+Xpbz+tyzd+92SmYRvJifFkttjGfNRDOrg39n9Qukq0PC/BKBGZlG8M6zioq4Hg8kM0aIs9PKn/raacN9X3Db5URuBCaWFj9CFfEj4wtpHxS/g5wZii0S9BJxKG3q7ZGyWPb8YXBP65yhCGBa2pbjPb+stti9uvulqS1U1oso/VADPy/oge3SWQ5/RjWBIEMJhVXPj1OmNverJbJjYM1JQOhEaPUA/LOu8Nwh6XVder3Vas7euitDggrjrAZWuNB+a4YOu4zyWw1JNCAQE40YznpUU9HbJ+D+E96d2xq6jHsHjWnOyCXQJI+Jnnk+LWotP37NdXKWe7yCKBHkV6PhhlcAbNUsDKYK/f1up9SMT1CVWDiitu+FRa9VIAToKYtDSjD/7hspaZ422ShM38RIdPlPmCXGgw/WyMaflMxyOcAqNNzirIjbRpu7uZrFq7LQ=
