#
#   INIT
#

#PARAMETERS
#If an option is missing, its default value will be assigned

njobs: 3

parameters:
  - parameter_name: 'CWL2'
    lha_block: 'dim6'
    lha_id: 2
    #morphing_max_power: 2
    param_card_transform: '16.52*theta'
    parameter_range: (-10.,10.)

  - parameter_name: 'CPWL2'
    lha_block: 'dim6'
    lha_id: 5
    morphing_max_power: 2
    param_card_transform: '16.52*theta'
    parameter_range: (-10.,10.)

#BENCHMARKS
#the number of paramaters for each benchmark must match 
#the number of paramaters introduced above 
benchmarks:
  - benchmark: 1
    parameter_name_1: 'CWL2'
    value_1: 0.
    parameter_name_2: 'CPWL2'
    value_2: 0.
    name: 'sm'

  - benchmark: 2
    parameter_name_1: 'CWL2'
    value_1: 10.
    parameter_name_2: 'CPWL2'
    value_2: 0.
    name: 'w'

#SETTINGS MORPHING
set_morphing:
  - setting: 1
    include_existing_benchmarks: True
    n_trials: 1000
    max_overall_power: 2


#
#   DELPHES
#

observables:
  - name: 'pt_j1'
    definition: 'j[0].pt'
    required: False
    default: 0. 

  - name: 'delta_phi_jj'
    definition: '(j[0].phi() - j[1].phi()) * (-1. + 2.*float(j[0].eta > j[1].eta))'
    required: True
    default:  

cuts:
  - cut: 1
    expression: 'pt_j1 > 30.'


#
#   ML
#


#SAMPLING

# if method in ['alice','alices','cascal','carl','rolr', 'rascal'] use
# method:
#   theta_0:
#     sampling_method: choose from 'benchmark(benchmark), benchmarks(benchmarks), 
#                                   morphing_point(theta), multiple_morphing_thetas(thetas), 
#                                   random_morphing_points(n_thetas, prior)'
#     
#     '''
#     schemas for all the sampling methods
#     '''
#     sampling_method: 'benchmark'
#       argument: 'name_of_benchmark'
#
#     sampling_method: 'benchmarks'
#       argument: ['list_of_benchmarks']
#
#     sampling_method: 'morphing_point'
#       argument: (n_parameters,)
#
#     sampling_method: 'multiple_morphing_thetas'
#       argument: (n_thetas, n_parameters)
#
#
#   theta_1:
#     '''
#     same schema as theta_0
#     '''
#
#
# if method in ['sally','sallino','scandal']
# method:
#   theta:
#   '''
#   same schema as theta_0
#   '''

shuffle: false

method: 'alices'

#theta_0:
#  sampling_method: 'benchmark' #'constant_benchmark_theta'
#  argument: 'w'

theta_0:
  sampling_method: 'random_morphing_points'
#  n_thetas: 100
#  prior:
#    parameter_0:
#      prior_shape: 'gaussian'
#      prior_param_0: 0. 
#      prior_param_1: 10. 
#    parameter_1:
#      prior_shape: 'gaussian'
#      prior_param_0: 0. 
#      prior_param_1: 10.
    #more pars

theta_1:
  sampling_method: 'benchmark'  #constant_benchmark_theta'
  argument: 'sm'


#TRAINING
n_samples:
  train: 100
  test: 100

test_split: 0.5

batch_size: 100

n_epochs: 2
