stages:

  - name: configurate
    dependencies: [init]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {stages: init, output: inputfile, unwrap: true}
      step: {$ref: 'steps.yml#/configurate'}

  - name: generate
    dependencies: [configurate]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {stages: init, output: inputfile, unwrap: true}
        config_file: {stages: configurate, output: config_file, unwrap: true}
        num_jobs: {stages: init, output: njobs}
        signal_dir: 'code/mg_processes/signal'
      step: {$ref: 'steps.yml#/generate'}

  - name: mgpythia
    dependencies: [generate]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        events_folder: {stages: generate, output: script_files, unwrap: true}
        madgraph_dir: 'software/MG5_aMC_v2_6_7'
        signal_dir: 'code/mg_processes/signal'
        logs_dir: 'code/logs'
      scatter:
        method: zip
        parameters: [eventfolder]
      step: {$ref: 'steps.yml#/mg_pythia'}

  - name: delphes
    dependencies: [mgpythia]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        config_file: {stages: configurate, output: config_file, unwrap: true}
        input_file: {stages: init, output: inputfile, unwrap: true}
        event_file: {stages: mgpythia, output: postrun_file, unwrap: true}
      step: {$ref: 'steps.yml#/delphes'}
      scatter:
        method: zip
        parameters: [eventfile]

  - name: combine
    dependencies: [delphes]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_files: {stages: delphes, output: dpostrun_file}
      step: {$ref: 'steps.yml#/combine'}


  - name: sampling
    dependencies: [combine]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        sampleworkdir: '{workdir}'
        n_trainsamples: {stages: init, output: ntrainsamples}
        input_file: {stages: init, output: inputfile, unwrap: true}
        data_file: {stages: combine, output: data_file, unwrap: true}
      step: {$ref: steps.yml#/sampling}
      
  - name: training
    dependencies: [sampling]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        trainworkdir: '{workdir}'
        input_file: {stages: init, output: inputfile, unwrap: true}
        trainfolder: {stages: sampling, output: sampling_file, unwrap: true}
      scatter:
        method: zip
        parameters: [trainfolder]
      step: {$ref: 'steps.yml#/training'}

  - name: evaluating
    dependencies: [training]
    scheduler:
      scheduler_type: multistep-stage
      parameters:
        trained_file: {stages: training, output: trained_file, unwrap: true}
        input_file: {stages: init, output: inputfile, unwrap: true}
        data_file: {stages: combine, output: data_file, unwrap: true}
        resultsfile: '{workdir}/Results.tar.gz'
        evalworkdir: '{workdir}'
      scatter:
        method: zip
        parameters: [trained_file]
      step: {$ref: 'steps.yml#/evaluating'}

  - name: plotting
    dependencies: [evaluating]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        results_file: {stages: evaluating, output: results_file, unwrap: true}
        input_file: {stages: init, output: inputfile, unwrap: true}
        plotworkdir: '{workdir}'
        outputfile: '{workdir}/outputfile.txt'
      step: {$ref: 'steps.yml#/plotting'}
