stages:
  - name: evaluating
    dependencies: [init]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        evalworkdir: '{workdir}'
        eval_folder: {step: init, output: evalfolder}
        input_evaluation: {step: init, output: inputevalfile}
        madminer_file: {step: init, output: madminerfile}
        outputfile: '{workdir}/outputfile.txt'
      step: {$ref: 'steps.yml#/evaluating'}


#stages:
#  - name: evaluating
#    dependencies: [init]
#    scheduler:
#      scheduler_type: singlestep-stage
#      parameters:
#        evalworkdir: '{workdir}'
#        input_evaluation: {step: init, output: inputevalfile}
#        
#        eval_folder_path: '/home/models'
#        outputfile: '{workdir}/outputfile.txt'
#      step: {$ref: 'steps.yml#/evaluating'}