stages:

  - name: workflow_ph
    dependencies: [init]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        input_file: {step: init, output: input_file_ph}
        num_jobs: {step: init, output: num_jobs}
      workflow: {$ref: 'ph/yadage/workflow.yml'}

  - name: workflow_ml
    dependencies: [workflow_ph]
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        data_file: {step: 'workflow_ph[*].combine', output: data_file}
        input_file: {step: init, output: input_file_ml}
        mlflow_server: {step: init, output: mlflow_server}
        train_samples: {step: init, output: train_samples}
      workflow: {$ref: 'ml/yadage/workflow.yml'}
